### ISSUE TITLE
docs pages render issue on gh-pages

### ISSUE THREAD

**Issue by anistark** [anistark/neptune#1]
When rendering `/docs` on gh-pages, only home page gets loaded. The other pages don't get loaded. But works all ok on local system.

**Comment by bgschiller** [comment]
It looks like only the `dist` folder is being pushed up to your `gh-pages` branch. Try changing the `build` script in your package.json to `rimraf dist && webpack --progress --profile --bail && cp -r docs/ dist/`

**Comment by anistark** [comment]
This has been worked upon and closed by @kincade71 with [PR](https://github.com/anistark/neptune/pull/3)
