### ISSUE TITLE
angular build issue

### ISSUE THREAD

**Issue by anistark** [anistark/neptune#2]
Angular not building properly.

How to replicate:
1. Build the angular app as given instruction in README.md file.
2. Run `dist`

**Comment by dinukadesilva** [comment]
I would like to work on this

**Comment by dinukadesilva** [comment]
@anistark currently this seems working correctly. It would be great if you could mention specifically which is needed to be fixed.

**Comment by anistark** [comment]
Currently, I've referred [https://anistark.github.io/neptune](https://anistark.github.io/neptune) to master/docs instead of gh-pages branch.

Steps to replicate:
* Fork the project
* Create your build with: `npm run build`
* Open `dist/index.html` in any browser

**Comment by amitgaikwad02bright** [comment]
what is status of this issue? i have also tried  but build is working fine..

**Comment by anistark** [comment]
Ah. This is resolved now.
